import type { NextPage } from 'next'
import Link from 'next/link'

import useSWR from 'swr'

import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { UserId } from './api/users'

const fetcher = (url: string) => fetch(url).then((res) => res.json())

const Home: NextPage = () => {
  const {data, error} = useSWR('/api/users', fetcher)
  if (error) return <div>Failed to load users</div>
  if (!data) return <div>Loading...</div>
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {data.map((user: UserId) => (
          <li key={user.id}>
          <Link href="/user/[id]" as={`/user/${user.id}`}>
            <a>{`User ${user.id}`}</a>
          </Link>
        </li>
        ))}
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

export default Home
